### ISSUE TITLE
Move subsampling rule before barcode trimming but after fastq cat-ting

### ISSUE THREAD

**Issue by kristinelacek** [nbx0/SC2-spike-seq#18]
This task is a great way to become familiar with the DAG and how rules flow into one another in a snakefile

The rule begins here https://github.com/nbx0/spyne/blob/prod/workflow/sc2_spike_snakefile#L108

And should be moved up to be after here https://github.com/nbx0/spyne/blob/prod/workflow/sc2_spike_snakefile#L28

You will need to change the input/output variables for the surrounding rules accordingly, and then repeat with the influenza_snakefile. I am happy to schedule a meeting soon to further explore the requisites and how to test your changes :)

The purpose of this change would be to make the earlier rules run a little faster with a smaller amount of input.

**Comment by nbx0** [comment]
Yay. Thanks @rchau88 !
